export default function AnalysisTab() {
  return (
    <div>
      {/* Question 2 */}
      <div>
        <h2 className="flex flex-col sm:flex-row sm:items-center font-medium gap-2 mb-4 text-sm sm:text-base">
          <div className="flex items-center justify-center w-7 h-7 rounded-full border-2 text-base font-normal bg-[#6c5ce7] text-white border-[#6c5ce7] shrink-0">
            2
          </div>
          <span className="mt-2 sm:mt-0">
            Write an email to your manager with your insights and suggest action
            items to improve activity results.
          </span>
        </h2>
        <div className="pb-14 md:pl-10">
          <textarea
            className="w-full h-60 p-3 sm:p-4 border border-gray-300 rounded-lg shadow-md focus:outline-none focus:ring-1 focus:ring-[#6c5ce7] resize-none"
            placeholder="Type your response..."
            name="q2"
            required
          />
        </div>
      </div>
      {/* Question 3 */}
      <div>
        <h2 className="flex flex-col sm:flex-row sm:items-center font-medium gap-3 mb-4 text-base md:text-lg sm:text-sm">
          <div className="flex items-center justify-center w-7 h-7 rounded-full border-2 text-base font-normal bg-[#6c5ce7] text-white border-[#6c5ce7] shrink-0">
            3
          </div>
          <span className="mt-2 sm:mt-0">
            Is it possible that one campaign has a better Depositor Ratio than
            another campaign, but its ROAS is lower?
          </span>
        </h2>
        <div className="space-y-2 sm:space-y-3 text-gray-500 pb-14 md:pl-10">
          {[
            "Yes, it depends on the ARPPU",
            "No, because the lower Depositor Ratio campaign generates less revenue",
            "No, because ROAS depends on the amount of depositors",
            "Yes, it depends on the daily budget",
          ].map((option, idx) => (
            <label
              key={idx}
              className="flex items-center space-x-2 text-[14px] sm:text-[15px]"
            >
              <input
                type="radio"
                name="q3"
                value={option}
                className="peer accent-[#6c5ce7] w-4 h-4 focus:ring-[#6c5ce7] shrink-0"
              />
              <span className="peer-checked:text-pink-500 transition-colors">{option}</span>
            </label>
          ))}
        </div>
      </div>
      {/* Question 4 */}
      <div>
        <h2 className="flex flex-col sm:flex-row sm:items-center font-medium gap-3 mb-4 text-base md:text-lg sm:text-base">
          <div className="flex items-center justify-center w-7 h-7 rounded-full border-2 text-base font-normal bg-[#6c5ce7] text-white border-[#6c5ce7] shrink-0">
            4
          </div>
          <span className="mt-2 sm:mt-0">
            Is it possible that one campaign has better ARPU than another
            campaign, but its ROAS is lower?
          </span>
        </h2>
        <div className="space-y-2 sm:space-y-3 text-gray-700 pb-14 md:pl-10">
          {[
            "Yes, it depends on the CPI",
            "No, because ROAS depends on the amount of depositors",
            "Yes, it depends on the amount of installs generated by each campaign",
          ].map((option, idx) => (
            <label
              key={idx}
              className="flex items-center space-x-2 text-[14px] sm:text-[15px]"
            >
              <input
                type="radio"
                name="q4"
                value={option}
                className="peer accent-[#6c5ce7] w-4 h-4 focus:ring-[#6c5ce7] shrink-0"
              />
              <span className="peer-checked:text-pink-500 transition-colors">{option}</span>
            </label>
          ))}
        </div>
      </div>
    </div>
  );
}
